### ISSUE TITLE
raspberry pi media server

### ISSUE THREAD

**Issue by mkeyno** [aelg/AMediaServer#1]
sorry to open ticket for my question , but I'm trying to let my raspberry pi connected client, share media files from storage connected to raspberry pi , I've already install NAS server but yet not figure out how to connect my file server (NAT, or FTP server) to such web GUI, can you advise me how to use your lib for such purpose or probably know the links who attempts to

**Comment by aelg** [comment]
Try editing *config.json*, the *videoDirs* variable should be set to a directory where your media files are.
If you're using a NAT I guess you should mount the storage somewhere on the raspberry pi and then set the videoDirs to that path.

**Comment by aelg** [comment]
I fixed a few bugs that seems to have come up recently. Might be working better now.

**Comment by mkeyno** [comment]
hi , after install dependency I copy the repo in the user directory but when I run run.py , following error come out
```cpp
pi@raspberrypi:~/Downloads/ami/AMediaServer-master $ python run.py
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/home/pi/Downloads/ami/AMediaServer-master/app/__init__.py", line 9, in <module>
    globalData.setPlayer(Player())
  File "/home/pi/Downloads/ami/AMediaServer-master/app/player.py", line 18, in __init__
    self.videoList = self.readVideos(globalData.config['videoListFile'])
  File "/home/pi/Downloads/ami/AMediaServer-master/app/player.py", line 26, in readVideos
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by aelg** [comment]
This seems to be because you are running python2? Python2 is unfortunately not supported. It seems to be almost there though if you'd like to fix it. I fixed the exception you have in your error, if that is changed the application seems to start. Then there seems to be problems with encoding of filenames, either it's because my system might have a bad locale setup or it's just that it's necessary to sprinkle `.encode('UTF-8')` and `.decode('UTF-8')` here and there if python2 is used. 

You can try the latest version, the error you mentioned above should be gone, but on my system I get encoding errors when I have video files/directories that have non-ascii characters in their names.

**Comment by mkeyno** [comment]
now I can't run pacman -S python-virtualenv omxplayer expect & virtualenv3 flask, are you sure about terms? beside I've installed both python 2 & 3 and all my program updated

**Comment by aelg** [comment]
I'm not sure of anything. If virtualenv, omxplayer and unbuffer (from expect) are installed you should only need to rerun virtualenv3 to get a python3 environment setup. If you are doing it in the same folder as before, you should remove the flask folder, as that will be created by doing `virtualenv3 flask`. 

The `pacman` command only works if you are using Arch Linux. On other linux distributions you need to install these dependencies yourself.
